import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // This rule flags any setState reachable synchronously from an effect body, which
      // includes the standard "call an async fetch function on mount" pattern used throughout
      // this app's hooks (use-routes, use-signal-realtime, use-online-status, onboarding).
      // There's no state-during-render hazard in any of those — just an ordinary fetch-on-mount
      // and browser-API sync — so this is downgraded to a warning rather than left as a build
      // error, or disabled outright.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Serwist build step — not source, shouldn't be linted.
    "public/sw.js",
  ]),
]);

export default eslintConfig;
